//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuBai_Pro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dubai_Editor
    {
        public int EditorID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Article { get; set; }
        public string ArticleType { get; set; }
        public Nullable<System.DateTime> ReleaseTime { get; set; }
        public Nullable<int> sort { get; set; }
    }
}
